-- ~/.config/hypr/hyprland.lua
-- Hyprland 0.55+ Lua config
-- https://wiki.hypr.land/Configuring/Start/

-- Colors auto-generated by matugen — run `matugen image <path>` to regenerate
local c = require("matugen/matugen-hyprland")

-- Sub-configs (all live in hyprconfigs/)
require("hyprconfigs/decorations_and_animations")
require("hyprconfigs/windowrules")
require("hyprconfigs/binds")
require("hyprconfigs/autostart")
require("hyprconfigs/gestures")

--------------------
---- MONITORS ------
--------------------

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@144",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output    = "HDMI-A-5",
    mode      = "1920x1080@60",
    -- transform = 4,          -- 90° counter-clockwise
    position  = "1920x-143",
    scale     = 1,
})

---------------------
---- WORKSPACES -----
---------------------

hl.workspace_rule({ workspace = 1, monitor = "eDP-1" })

---------------------
---- ENVIRONMENT ----
---------------------

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

----------------
---- CURSOR ----
----------------

hl.config({
    cursor = {
        inactive_timeout = 5,
    },
})

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout     = "us",
        sensitivity   = 2,
        follow_mouse  = 1,
        scroll_method = "2fg",

        touchpad = {
            natural_scroll       = false,
            disable_while_typing = false,
            tap_to_click         = true,
            scroll_factor        = 1.5,
        },
    },
})

--------------
---- MISC ----
--------------

hl.config({
    misc = {
        disable_hyprland_logo = false,
        focus_on_activate     = true,
        enable_swallow        = true,
        swallow_regex         = "^(kitty)$",
          session_lock_xray     = true,
    },
})

hl.config({
    general = {
        allow_tearing    = true,
        gaps_in          = 10,
        gaps_out         = 10,
        border_size      = 1,
        resize_on_border = true,

        col = {
            active_border         = { colors = { c.primary_container, c.outline }, angle = 45 },
            inactive_border       = { colors = { c.background,        c.outline }, angle = 45 },
            nogroup_border        = 0xff89dceb,  -- fixed: was 9-digit 0xff089dceb
            nogroup_border_active = 0xfff9e2af,
        },

    },
})

-- Dwindle confs
hl.config({
    general = {
        layout = "dwindle",
    },
    
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})
