-- Auto-generated by matugen — DO NOT EDIT MANUALLY
-- Regenerated every time you run: matugen image <path>
--
-- Template : ~/.config/matugen/templates/matugen-hyprland.lua
-- Output   : ~/.config/hypr/matugen/matugen-hyprland.lua

local M = {}

M.image = "/home/jack/wallpapers/static_unsorted_wallpapers/pexels-quang-nguyen-vinh-2649403.jpg"


M.background = "rgba(101418ff)"

M.error = "rgba(ffb4abff)"

M.error_container = "rgba(93000aff)"

M.inverse_on_surface = "rgba(2d3135ff)"

M.inverse_primary = "rgba(32628dff)"

M.inverse_surface = "rgba(e0e2e8ff)"

M.on_background = "rgba(e0e2e8ff)"

M.on_error = "rgba(690005ff)"

M.on_error_container = "rgba(ffdad6ff)"

M.on_primary = "rgba(003355ff)"

M.on_primary_container = "rgba(cfe5ffff)"

M.on_primary_fixed = "rgba(001d34ff)"

M.on_primary_fixed_variant = "rgba(134a74ff)"

M.on_secondary = "rgba(243240ff)"

M.on_secondary_container = "rgba(d6e4f7ff)"

M.on_secondary_fixed = "rgba(0f1d2aff)"

M.on_secondary_fixed_variant = "rgba(3a4857ff)"

M.on_surface = "rgba(e0e2e8ff)"

M.on_surface_variant = "rgba(c2c7cfff)"

M.on_tertiary = "rgba(392a49ff)"

M.on_tertiary_container = "rgba(f0dbffff)"

M.on_tertiary_fixed = "rgba(241532ff)"

M.on_tertiary_fixed_variant = "rgba(514060ff)"

M.outline = "rgba(8c9199ff)"

M.outline_variant = "rgba(42474eff)"

M.primary = "rgba(9dcbfcff)"

M.primary_container = "rgba(134a74ff)"

M.primary_fixed = "rgba(cfe5ffff)"

M.primary_fixed_dim = "rgba(9dcbfcff)"

M.scrim = "rgba(000000ff)"

M.secondary = "rgba(bac8daff)"

M.secondary_container = "rgba(3a4857ff)"

M.secondary_fixed = "rgba(d6e4f7ff)"

M.secondary_fixed_dim = "rgba(bac8daff)"

M.shadow = "rgba(000000ff)"

M.source_color = "rgba(022c4aff)"

M.surface = "rgba(101418ff)"

M.surface_bright = "rgba(36393eff)"

M.surface_container = "rgba(1d2024ff)"

M.surface_container_high = "rgba(272a2fff)"

M.surface_container_highest = "rgba(32353aff)"

M.surface_container_low = "rgba(191c20ff)"

M.surface_container_lowest = "rgba(0b0e12ff)"

M.surface_dim = "rgba(101418ff)"

M.surface_tint = "rgba(9dcbfcff)"

M.surface_variant = "rgba(42474eff)"

M.tertiary = "rgba(d4bee6ff)"

M.tertiary_container = "rgba(514060ff)"

M.tertiary_fixed = "rgba(f0dbffff)"

M.tertiary_fixed_dim = "rgba(d4bee6ff)"


return M
